# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=b'Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name=b'Modified')),
                ('code', models.TextField(help_text=b'This is where you put your obfuscated code. :P', verbose_name=b'Codez')),
                ('code_highlight', models.TextField(blank=True, editable=False, verbose_name=b'Highlighted Code')),
                ('lexer', models.CharField(blank=True, choices=[(b'bash', b'Bash'), (b'brainfuck', b'Brainfuck'), (b'c', b'C'), (b'clojure', b'Clojure'), (b'cpp', b'C++'), (b'csharp', b'C#'), (b'css', b'CSS'), (b'd', b'D'), (b'erlang', b'Erlang'), (b'go', b'Go'), (b'haskell', b'Haskell'), (b'html', b'HTML'), (b'html+php', b'PHP'), (b'java', b'Java'), (b'js', b'JavaScript'), (b'lua', b'Lua'), (b'ocaml', b'OCaml'), (b'perl', b'Perl'), (b'python', b'Python'), (b'ruby', b'Ruby'), (b'scala', b'Scala'), (b'scheme', b'Scheme'), (b'smalltalk', b'Smalltalk'), (b'sql', b'SQL'), (b'text', b'Text'), (b'xml', b'XML')], default=b'python', help_text=b"Specify a language. We'll try to guess it otherwise. (This works best with a shebang.)", max_length=255, null=True, verbose_name=b'Language')),
                ('expires_options', models.IntegerField(blank=True, choices=[(60, b'One Minute'), (3600, b'One Hour'), (604800, b'One Week'), (2592000, b'One Month')], help_text=b'When to expire =(', null=True, verbose_name=b'Expires')),
                ('expires_date', models.DateTimeField(blank=True, null=True, verbose_name=b'Expires Date')),
                ('url', models.SlugField(blank=True, max_length=255, verbose_name=b'URL')),
                ('locked', models.BooleanField(default=0, help_text=b"Lock so it can't be edited.", verbose_name=b'Lock')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
